In [18]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sb

In [6]:
data = [[1, 'Joe', 70000, 3], [2, 'Henry', 80000, 4], [3, 'Sam', 60000, None], [4, 'Max', 90000, None]]
employee = pd.DataFrame(data, columns=['id', 'name', 'salary', 'managerId']).astype({'id':'Int64', 'name':'object', 'salary':'Int64', 'managerId':'Int64'})

employee.head()

   id   name  salary  managerId
0   1    Joe   70000          3
1   2  Henry   80000          4
2   3    Sam   60000       <NA>
3   4    Max   90000       <NA>

In [36]:
df = employee.merge(right=employee, how='left', left_on='managerId', right_on='id')
df.head()

   id_x name_x  salary_x  managerId_x  id_y name_y  salary_y  managerId_y
0     1    Joe     70000            3     3    Sam     60000         <NA>
1     2  Henry     80000            4     4    Max     90000         <NA>
2     3    Sam     60000         <NA>  <NA>    NaN      <NA>         <NA>
3     4    Max     90000         <NA>  <NA>    NaN      <NA>         <NA>

In [37]:
data = [[1, 'Joe'], [2, 'Henry'], [3, 'Sam'], [4, 'Max']]
customers = pd.DataFrame(data, columns=['id', 'name']).astype({'id':'Int64', 'name':'object'})
data = [[1, 3], [2, 1]]
orders = pd.DataFrame(data, columns=['id', 'customerId']).astype({'id':'Int64', 'customerId':'Int64'})

orders.head()

   id  customerId
0   1           3
1   2           1

In [5]:
customers.head()

   id   name
0   1    Joe
1   2  Henry
2   3    Sam
3   4    Max

In [53]:
df = customers.merge(right=orders, how='left', left_on='id', right_on='customerId')
df = df.rename(columns={"name" : "Name"})
df.head()
names = df[df["customerId"].isna()]
names[["Name"]].head()

    Name
1  Henry
3    Max